-- up
CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  role VARCHAR(50) NOT NULL DEFAULT 'admin',
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT IGNORE INTO users (email, password, name, role)
VALUES ('admin@portfolio.com', '$2a$10$WXieh8EVyXKZclLxfq5f2OW0/w2cTP14HUUFcfY4Ch4ynabQ1dsyW', 'Admin User', 'admin'); -- 12345678

-- down
DROP TABLE IF EXISTS users;
